<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" PrivateAssets="all" />
    <PackageReference Include="Tenantry.Core" Version="$(TenantryCoreVersion)" />
    <PackageReference Include="Tenantry.AspNetCore" Version="$(TenantryCoreVersion)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Tenantry.Pro" Version="$(TenantryProVersion)" />
    <PackageReference Include="Tenantry.Pro.EfCore" Version="$(TenantryProVersion)" />
  </ItemGroup>

</Project>
